services:
  client:
    image: "ginuerzh/gost:latest"
    command: "-L socks5://:1442 -F 'mwss://${USER}:${PASSWORD}@${DOMAIN}:${PORT}'"
    ports:
      - "1442:1442"
    env_file:
      - path: .env
        required: true
  client2:
    image: "ginuerzh/gost:latest"
    command: "-L socks5://:1443 -F 'mwss://${USER}:${PASSWORD}@${DOMAIN}:${PORT_WITH_WARP}'"
    ports:
      - "1443:1443"
    env_file:
      - path: .env
        required: true